### ISSUE TITLE
action method parameter cache

### ISSUE THREAD

**Issue by dreamingo88** [actframework/actframework#1054]
test with crud:
1. POST http://localhost:5460/api/v1/bookmark/show/
this step is very important, with a null id. 
error::: npe

2. POST http://localhost:5460/api/v1/bookmark/show/{random id}
then, change id, still npe.

**Comment by greenlaw110** [comment]
The root cause is inside the following logic:

```java
    JsonParamValueLoader(ParamValueLoader fallBack, BeanSpec spec, DependencyInjector<?> injector) {
        this.fallBack = $.requireNotNull(fallBack);
        this.spec = $.requireNotNull(spec);
        this.defValProvider = findDefValProvider(spec, injector);
        ActionContext ctx = ActionContext.current();
        if (null != ctx) {
            isPathVariable = ctx.isPathVar(spec.name());
        }
    }
```

In the first time it requests the URL there is no path variable specified, thus `isPathVariable` get initialized to `false`, which makes it not looking for path variable for the following requests, even when the path variable is presented.

To fix the issue we can't make `isPathVariable` locked, instead we need to sacrifice as little bit performance to check if path variable is presented at each request.
