### ISSUE TITLE
`ISObject` is not null when no file is uploaded

### ISSUE THREAD

**Issue by donald2150** [actframework/actframework#1083]

**Comment by donald2150** [comment]
```
<input type="file" name="file"/>
<input type="text" name="fileName"/>

java
public void save(ISObject file){}

**Comment by greenlaw110** [comment]
Root cause

When no file upload found, the framework still try to resolve string "file" into an `ISObject` instance through base64 decoding:
![image](https://user-images.githubusercontent.com/216930/54787900-50b45b00-4c81-11e9-9da2-b34bf5a25d55.png)

Solution:

when the string length is less than 15 characters then we assume it is a variable name and return null directly:
![image](https://user-images.githubusercontent.com/216930/54798364-8cb0e580-4cac-11e9-8e84-ce4fccebbc83.png)
