### ISSUE TITLE
Change Content-Type header for JSON error response

### ISSUE THREAD

**Issue by oshatrk** [actframework/actframework#1173]
Act 1.8.25.

Currently the "Content-Type" header of an error response isn't corrected after its content type is changed to JSON by Act logic in [ActErrorPageRender.fixRequestAcceptFormat()](https://github.com/actframework/actframework/blob/cfe8a13b557f543ed58474086b90402ddecdec33/src/main/java/act/util/ActErrorPageRender.java#L108-L113)

For example for this action:

```java
    @GetAction("/doit")
    @ResponseContentType(H.MediaType.TXT) // Is changed by Act to JSON in case of error
    public String doit(int param1) {
        return "I'am OK...\n";
    }
```

With `curl -i "http://localhost:5460/doit?param1=incorrect"` the output is:

```
HTTP/1.1 400 Bad Request
Server: HWD-/1.0-SNAPSHOT
Content-Type: text/plain
Content-Length: 62
Date: Sun, 21 Jul 2019 11:20:23 GMT

{"ts":1563708023680,"message":"For input string: "incorrect""}
```

(`curl` requests with "Accept: \*/\*" by default).

Note the response body is in JSON format but the "Content-Type" header is "text/plain".

This happens if:

* there is no HTML, JSON, XML or CSV in a request's "Accept" header ("Accept: \*/\*" is also treated as UNKNOWN by [H.Format.resolve_()](https://github.com/osglworks/java-http/blob/707a349e23cb84efe19d15d4c3dc408bb1e94a9f/src/main/java/org/osgl/http/H.java#L1475))

_AND_ 
{
* the response content type is forced with `@ResponseContentType()` annotation to TXT, CSS, JAVASCRIPT, and possibly other text types determined by [H.Format.isText()](https://github.com/osglworks/java-http/blob/707a349e23cb84efe19d15d4c3dc408bb1e94a9f/src/main/java/org/osgl/http/H.java#L1318-L1325) used by [ActionContext.contentTypeForErrorResult()](https://github.com/actframework/actframework/blob/f2fc556e26d82e63384d06b48200a0d09738bbfc/src/main/java/act/app/ActionContext.java#L942-L953) except for HTML, JSON, XML, CSV as they are allowed types for error replies ([ActErrorPageRender.isAcceptGoodForErrorPage()](https://github.com/actframework/actframework/blob/cfe8a13b557f543ed58474086b90402ddecdec33/src/main/java/act/util/ActErrorPageRender.java#L108-L113))

_OR_ 

* there is no `@ResponseContentType()` annotation and no "X-Requested-With:XMLHttpRequest" header in request.

}

(If "Accept" header doesn't contain HTML, JSON, XML or CSV _AND_ there is no `@ResponseContentType()` annotation _AND_ request has "X-Requested-With:XMLHttpRequest" then the error response content is HTML and header is set to "Content-Type: text/html" correctly).

The solution for this issue can be as simple as:

```java
    private void fixRequestAcceptFormat(ActionContext context) {
        H.Request req = context.req();
        if (null != req && !isAcceptGoodForErrorPage(req.accept())) {
            req.accept(H.Format.JSON);
            context.resp()
                    .contentType(context.req().accept())
                    .commitContentType();
        }
    }
```

But I'm not sure with correctness of this code. So Your commit is preffered.

P.S: Note also another minor bug in the example response — inner quotes in message aren't escaped by [ActErrorPageRender.jsonContent()](https://github.com/actframework/actframework/blob/cfe8a13b557f543ed58474086b90402ddecdec33/src/main/java/act/util/ActErrorPageRender.java#L127-L131).

**Comment by greenlaw110** [comment]
@oshatrk I think it is totally okay if to treat a JSON content as text/plain (which is forced by `@ResponseContentType(H.MediaType.TXT)`) in your sample code, because JSON content itself is a piece of text, and it by naturally most readable error response in this case.

However I do need to fix the JSON message escape issue.

**Comment by oshatrk** [comment]
@greenlaw110 My example with TXT type isn't contrast enough. So let change it to CSS:
```
    @GetAction("/is_it_json_or_css")
    @ResponseContentType(H.MediaType.CSS)
    public void is_it_json_or_css() {
        throw Util.badRequest();
    }
```
```
# curl -i "http://localhost:5460/is_it_json_or_css"

HTTP/1.1 400 Bad Request
Server: HWD-/1.0-SNAPSHOT
Content-Type: text/css
Content-Length: 100
Date: Mon, 22 Jul 2019 16:02:02 GMT

{"ts":1563811322583,"message":"Bad Request on invoking com.example.HelloWorldApp.is_it_json_or_css"}
```
The Content-Type header isn't correct here, is it?

BTW I assume the fix required will help a little with possible future upgrade from `application/json` to `application/problem+json` for error results.

**Comment by greenlaw110** [comment]
@oshatrk spot on! Look here is a good example of grey area of design where it is a hard to justify the right solution. 

I would say in case there error encountered when user request `text/css`, it put the framework in a very bad situation because there is no way to express an error in CSS, same issue with `image/png`, or many other media type like `audio` or `video` etc. In which case we will probably force to change the response type to one of the solution that able to convey the error message, like `application/problem+json`

However if developer requested a mime type that is able to express error message, e.g. `text/html` or even `text/csv`, there is no reason to force the response change to `application/problem+json`, this include `text/plain`. What do you think?
