### ISSUE TITLE
How to configuration multi cookie domain

### ISSUE THREAD

**Issue by jiankian** [actframework/actframework#1402]
My Web App need to support multi domain, documentation id lost

**Comment by greenlaw110** [comment]
Here is one possible solution:

1. Setup your nginx conf so that it [forward the domain name](https://stackoverflow.com/questions/12464241/how-to-proxy-proxy-domain-name-to-internal-app-server-url-in-nginx) to your act app. Note you must use `X-Forwarded-Host` to forward the domain name.
2. Configure your AppConfig with a special cookieDomainProvider that returns domain prefix contains the `ActionContext.req().domain()`.
