### ISSUE TITLE
Where is the mail template location?

### ISSUE THREAD

**Issue by mezongzi** [actframework/actframework#201]
How to specify the location of Mail template, what if I want to send out email with template?

**Comment by greenlaw110** [comment]
The location of mail template is exactly the same as the location of controller template. For example,

```java
package x.y;

@Mailer
public class PostOffice extends Mailer.Util {

    @Inject
    private AppCrypto crypto;

    public void sendWelcomeLetter(User user) {
        to(user.email);
        String tk = crypto.generateToken(Token.Life.ONE_DAY, user.email);
        subject("Welcome to XY system");
        send(user, tk);
    }

}
```

In the above example, the location of your email template for welcome letter should be

```
/resources/<template-engine-id>/x/y/PostOffice/sendWelcomeLetter.html
```

By default `<template-engine-id>` is `rythm`.

If you want to explicitly specify the mail template, use the same strategy as you specify the action handler template by passing a string literal into the `send()` API as the first parameter. Make sure you use string literal instead of string variable, otherwise the framework will treat it as a template argument:

```java

    public void sendWelcomeLetter(User user) {
        to(user.email);
        String tk = crypto.generateToken(Token.Life.ONE_DAY, user.email);
        subject("Welcome to XY system");
        send("/mail/welcome.html", user, tk);
    }
```

At the moment ActFramework does not support sending email without template. Please file a feature request if you need it.

**Comment by mezongzi** [comment]
thinks
