### ISSUE TITLE
ACT can only map wrapped JSON object to entity

### ISSUE THREAD

**Issue by leeaee** [actframework/actframework#383]
ACT MVC could not map the flat json object to java entity. When request user object, ''user" is null.
UserApi.java
```java
public User create(User user) {
    return user;
}
```
Request JSON Object could not map to User entity
```json
{
    "username":"test",
    "password":"111111"
}
```
Request JSON object can map to User entity
```json
{
    "user":
    {
        "username":"test",
        "password":"111111"
    }
}

**Comment by greenlaw110** [comment]
This is caused by interceptor signature, for example, if you have a global interceptor:

```java
public class SuperInterceptor {

    private String foo;

    @Global
    @Before
    public void checkFooWithBar(String bar) {...}

}
```

Because `SuperInterceptor::checkFooWithBar(String)` method is a global before interceptor, and it is invoked before `create(User)` handler, thus JSON object is evaluated on calling `SuperInterceptor::checkFooWithBar(String)` method.

Unfortunately ActFramework is using `JsonDTO.CTX_ATTR_KEY` to cache the evaluated DTO object, and when it get down to `create(User)` handler, it found there is already a DTO object generated, and thus use it directly, which obviously is not suitable for the case.

The solution is 

1. do not cache JSON DTO during interceptor and handler method invocation
2. (optionally) disable JSON DTO evaluation on interceptor methods unless developer mark the interceptor needs evaluate the incoming data
