### ISSUE TITLE
Ebean <model> is not enchaned?

### ISSUE THREAD

**Issue by jiankian** [actframework/actframework#545]
Found on `1.6.7` till `1.8.0`. It works on `1.6.6`.

The following project can be used to reproduce the issue：https://github.com/jiankian/todo-eben2

**Comment by greenlaw110** [comment]
# Root cause analysis:

The db configuration file:

```
db.instances=mysql

db.mysql.impl=act.db.ebean2.EbeanPlugin
db.mysql.driver=com.mysql.cj.jdbc.Driver
db.mysql.url=jdbc:mysql://localhost:3306/act_todo?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
db.mysql.username=...
db.mysql.password=...
```

As a single db instance `mysql` is provided, it is treated as the `default` db instance. The new entity scanner use the name `default` to persist the entity bean information scanned. While the consumer of the meta information use the name `mysql` to search for meta info, and `null` is returned obviously:

![image](https://user-images.githubusercontent.com/216930/36954442-2d3ae46a-2076-11e8-83fc-8782136a14e8.png)

**Comment by greenlaw110** [comment]
Before `1.8.1` released, here is the workaround: just change the db.properties files to:

```
db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://localhost:3306/act_todo?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
db.username=...
db.password=...
```
