### ISSUE TITLE
Cannot get parameter

### ISSUE THREAD

**Issue by dai875939260** [actframework/actframework#624]
form data：

```
idList[]: 117212
```

Source code

```java
@Param("idList[]") String[] ids
```

**Comment by greenlaw110** [comment]
Instead of using 

```java
@Param("idList[]") String[] ids
```

try

```java
@Param("idList") String[] ids
```

Note you must remove `[]` from param name `idList`.

A better way is to use `javax.inject.Named` to replace `Param`

```java
@Named("idList") String[] ids
```

The best way is to make your method parameter name be the same as your form field name and get rid of annotation:

```java
String[] idList
```

Reproduce project:

https://github.com/greenlaw110/act-github-issues/tree/gh624

**Comment by dai875939260** [comment]
嗯，我已经自己探索到了。还有个问题是，加入我定义了binder解析，在controller就无法再次获取参数了吗
```java
// binder
    @Override
    public PageQuery resolve(PageQuery bean, String model, ParamValueProvider params) {
        PageQuery pageQuery = new PageQuery();
        Set<String> paramKeys = params.paramKeys();
        for (String paramKey : paramKeys) {
            ....
        }
        return pageQuery;
    }
// controller
public void test(PageQuery pageQuery,String param1...){
// param1 is null
}
```

**Comment by greenlaw110** [comment]
Binder 就是在解析请求处理方法参数的时候使用的啊. 不明白你的意思.

**Comment by dai875939260** [comment]
我又测试了一遍，这种情况只会在新加的一些代码没有重启的情况出现，导致我以为是写法问题。看来我要提问题前先重启了试试。
![image](https://user-images.githubusercontent.com/6057326/38776006-5ae73ce4-40c2-11e8-9fdc-dff4d009821e.png)

**Comment by greenlaw110** [comment]
那就还是有问题, Act 的设计是代码更改应该立刻生效才对. 你能给出详细步骤让我重现这个错误吗?

**Comment by greenlaw110** [comment]
close as no response from issue submitter
